import React from 'react';

const REPORT_ROWS=['MENUDEO','FLOTILLA','SUAUTO','VENTAS DEMO','VENTAS CASA','PEND DE FACT','REFACTURACION'];
const norm=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
const isDelivered=row=>norm(row.status)==='ENTREGADA'||Boolean(row.actualDate);
const isCancelled=row=>norm(row.status)==='CANCELADA';
const category=row=>{const type=norm(row.saleType);if(type.includes('FLOT'))return'FLOTILLA';if(type.includes('SUAUTO'))return'SUAUTO';if(type.includes('DEMO'))return'VENTAS DEMO';if(type.includes('CASA'))return'VENTAS CASA';if(type.includes('PEND'))return'PEND DE FACT';if(type.includes('REFACT'))return'REFACTURACION';return'MENUDEO';};
const count=(rows,predicate)=>rows.filter(predicate).length;
const pct=(value,total)=>total?`${(value/total*100).toFixed(2)}%`:'0.00%';
const displayDate=month=>{const [year,number]=String(month||'').split('-').map(Number);const date=year&&number?new Date(year,number-1,1):new Date();return new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric'}).format(date);};
const MODERN_REPORT_CSS=`.delivery-report-suite{font-family:inherit}.delivery-report{border:1px solid #d7e2f0;border-radius:16px;box-shadow:0 10px 28px rgba(15,47,99,.06)}.delivery-report>header,.delivery-report.chs>header{padding:16px 20px;background:linear-gradient(135deg,#0f2f63,#2563eb);color:#fff}.delivery-report>header h3,.delivery-report>header span{color:#fff}.delivery-report>header h3{font-size:17px;letter-spacing:.04em}.delivery-report-matrix th,.delivery-report-matrix td{padding:9px 8px;border:1px solid #dbe5f2;font-family:inherit;font-size:9px}.delivery-report-matrix thead th{background:#eff4fb;color:#405675}.delivery-report-matrix thead .branch-head{background:#163d77;color:#fff;font-size:10px;letter-spacing:.05em}.delivery-report-matrix thead .manager{background:#dce8f8;color:#173d78;font-size:9px}.delivery-report-matrix thead .manager.house{background:#ede9fe;color:#6d28d9}.delivery-report-matrix thead th.delivered,.delivery-report-matrix td.delivered{background:#e2f8f0;color:#08785c}.delivery-report-matrix tbody th{background:#f8fafc;color:#334155;font-size:9px}.delivery-report-matrix tbody tr:hover td{background:#f3f7fd}.delivery-report-matrix td.total{background:#e8f0ff;color:#174ea6}.delivery-report-matrix tr.grand>*{background:#dce8fb;color:#103b78}.delivery-report-matrix tr.grand>.delivered{background:#d5f5e9;color:#08785c}.delivery-mini{border:1px solid #d7e2f0;border-radius:12px;box-shadow:0 7px 18px rgba(15,47,99,.05)}.delivery-mini h4,.delivery-mini-grid.chs-grid .delivery-mini h4{padding:10px 11px;background:#173d78;color:#fff;font-family:inherit;font-size:9px;letter-spacing:.04em}.delivery-mini th,.delivery-mini td{padding:8px;border:1px solid #e3eaf4;font-family:inherit;font-size:9px}.delivery-mini tr.positive{color:#08785c}.delivery-mini tr.warning td{background:#fff3cd;color:#9a6700}.delivery-mini tr.strong td{background:#d5f5e9;color:#08785c}.delivery-mini.market thead th{background:#eff4fb;color:#526884}.delivery-mini.market tbody tr{color:#173d78}.delivery-report-suite-title{box-shadow:0 8px 22px rgba(15,47,99,.05)}`;

function MiniTable({title,rows,tone='green'}){
  return <article className={`delivery-mini ${tone}`}><h4>{title}</h4><table><tbody>{rows.map(([label,value,kind])=><tr key={label} className={kind||''}><th>{label}</th><td>{value}</td></tr>)}</tbody></table></article>;
}

function OperationsMatrix({title,rows,groups,tone}){
  const totals=groups.map(group=>({fact:count(rows,row=>group.match(row)&&!isCancelled(row)),del:count(rows,row=>group.match(row)&&isDelivered(row))}));
  const branchHeaders=groups.reduce((list,group)=>{const current=list[list.length-1];if(current?.name===group.branch)current.span+=2;else list.push({name:group.branch,span:2});return list;},[]);
  return <section className={`delivery-report ${tone}`}>
    <header><h3>{title}</h3><span>{displayDate(rows[0]?.invoiceDate?.slice(0,7))}</span></header>
    <div className="delivery-report-scroll"><table className="delivery-report-matrix"><thead><tr><th rowSpan="3" className="stub">TIPO DE OPERACIÓN</th>{branchHeaders.map(branch=><th key={branch.name} colSpan={branch.span} className="branch-head">{branch.name}</th>)}<th rowSpan="3">TOTAL<br/>FACTURADO</th><th rowSpan="3">TOTAL<br/>ENTREGADO</th></tr><tr>{groups.map(group=><th key={group.key} colSpan="2" className={`manager ${group.house?'house':''}`}>{group.manager}</th>)}</tr><tr>{groups.flatMap(group=>[<th key={`${group.key}-f`}>FACTURADAS</th>,<th key={`${group.key}-e`} className="delivered">ENTREGADAS</th>])}</tr></thead>
      <tbody>{REPORT_ROWS.map(label=>{const cells=groups.map(group=>{const filtered=rows.filter(row=>group.match(row)&&category(row)===label&&!isCancelled(row));return{fact:filtered.length,del:count(filtered,isDelivered)};});return <tr key={label}><th>{label}</th>{cells.flatMap((cell,index)=>[<td key={`${index}-f`}>{cell.fact||''}</td>,<td key={`${index}-e`} className="delivered">{cell.del||''}</td>])}<td className="total">{cells.reduce((sum,item)=>sum+item.fact,0)}</td><td className="total delivered">{cells.reduce((sum,item)=>sum+item.del,0)}</td></tr>;})}<tr className="grand"><th>TOTAL VTAS. GLOBAL</th>{totals.flatMap((cell,index)=>[<td key={`${index}-f`}>{cell.fact}</td>,<td key={`${index}-e`} className="delivered">{cell.del}</td>])}<td>{totals.reduce((sum,item)=>sum+item.fact,0)}</td><td className="delivered">{totals.reduce((sum,item)=>sum+item.del,0)}</td></tr></tbody></table></div>
  </section>;
}

export default function DeliveryReportTables({records=[],selectedMonth,branchCatalog=[],teams=[]}){
  const source=records.filter(row=>!selectedMonth||String(row.invoiceDate||'').startsWith(selectedMonth));
  const toro=source.filter(row=>!norm(row.branch).startsWith('CHS'));
  const chs=source.filter(row=>norm(row.branch).startsWith('CHS'));
  const today=new Date().toISOString().slice(0,10);
  const activeBranches=(branchCatalog||[]).filter(branch=>branch?.active!==false&&branch?.name).map(branch=>branch.name);
  const catalogBranches=activeBranches.length?activeBranches:[...new Set(source.map(row=>row.branch).filter(Boolean))];
  const makeGroups=branchNames=>branchNames.flatMap(branch=>{const managers=[...new Set((teams||[]).filter(team=>team?.inactive!==true&&norm(team.sucursal||team.branch)===norm(branch)).map(team=>team.manager).filter(Boolean))];const effectiveManagers=managers.length?managers:[...new Set(source.filter(row=>norm(row.branch)===norm(branch)).map(row=>row.manager).filter(Boolean))];const managerGroups=effectiveManagers.map(manager=>({key:`${branch}-${manager}`,branch,manager,match:row=>norm(row.branch)===norm(branch)&&norm(row.manager)===norm(manager)&&category(row)!=='VENTAS CASA'}));return[...managerGroups,{key:`${branch}-CASA`,branch,manager:'CASA',house:true,match:row=>norm(row.branch)===norm(branch)&&category(row)==='VENTAS CASA'}];});
  const toroGroups=makeGroups(catalogBranches.filter(branch=>!norm(branch).startsWith('CHS')));
  const chsGroups=makeGroups(catalogBranches.filter(branch=>norm(branch).startsWith('CHS')));
  const deliveredToro=toro.filter(isDelivered),pendingToro=toro.filter(row=>!isDelivered(row)&&!isCancelled(row));
  const deliveredChs=chs.filter(isDelivered),pendingChs=chs.filter(row=>!isDelivered(row)&&!isCancelled(row));
  const brandRows=['GMC','CADILLAC','BUICK'].map(brand=>[brand,count(chs,row=>norm(row.brand)===brand&&!isCancelled(row)),count(chs,row=>norm(row.brand)===brand&&isDelivered(row))]);
  const participation=['SUV','PICK UP / VAN'].map(line=>{const advance=count(toro,row=>norm(row.classification)===line&&!isCancelled(row));return[line,'—',advance,'Pendiente'];});

  return <section className="delivery-report-suite">
    <div className="delivery-report-suite-title"><div><span>REPORTE OPERATIVO</span><h3>Tablas ejecutivas de facturación y entregas</h3><p>Estructura homologada al reporte diario. Los conceptos especiales quedan listos para enlazar su fuente exacta.</p></div><b>{displayDate(selectedMonth)}</b></div>
    <OperationsMatrix title="REPORTE TORO" rows={toro} groups={toroGroups} tone="toro"/>
    <div className="delivery-mini-grid toro-grid">
      <MiniTable title="ENTREGAS DEL DÍA" rows={[["(+) ENTREGAS REALES",count(deliveredToro,row=>row.actualDate===today),'positive'],['(+) DEMOS OUT',count(pendingToro,row=>category(row)==='VENTAS DEMO')],['(-) DEMOS FACTURADOS',count(deliveredToro,row=>category(row)==='VENTAS DEMO')],['(-) FLOTILLAS',count(deliveredToro,row=>category(row)==='FLOTILLA')],['(-) PENDIENTES X REPORTAR',pendingToro.length,'warning'],['REPORTADAS HOY',count(deliveredToro,row=>row.actualDate===today),'positive']]}/>
      <MiniTable title="ENTREGAS FLOTILLAS" rows={[["(+) ENTREGAS REALES",count(deliveredToro,row=>category(row)==='FLOTILLA'),'positive'],['(-) PENDIENTES X REPORTAR',count(pendingToro,row=>category(row)==='FLOTILLA'),'warning'],['REPORTADAS EN EL MES',count(deliveredToro,row=>category(row)==='FLOTILLA'),'positive']]}/>
      <MiniTable title="ENTREGAS DEMOS" rows={[["(+) ENTREGAS REALES",count(deliveredToro,row=>category(row)==='VENTAS DEMO'),'positive'],['DEMO OUT (SIN ENTREGAR)',count(pendingToro,row=>category(row)==='VENTAS DEMO'),'warning']]}/>
      <MiniTable title="ENTREGAS MENUDEO" rows={[["(+) ENTREGAS REALES",count(deliveredToro,row=>category(row)==='MENUDEO'),'positive'],['(-) REPORTE ANTERIOR','—'],['(+) DEMOS OUT',count(pendingToro,row=>category(row)==='VENTAS DEMO')],['(-) PENDIENTES X REPORTAR',pendingToro.length,'warning'],['REPORTADAS MENUDEO',count(deliveredToro,row=>category(row)==='MENUDEO')],['REFERENCIA DEL MES','—'],['PORCENTAJE ENTREGADO',pct(deliveredToro.length,toro.filter(row=>!isCancelled(row)).length),'strong']]}/>
      <article className="delivery-mini market"><h4>PARTICIPACIÓN DE MERCADO</h4><table><thead><tr><th>LÍNEA</th><th>REFERENCIA</th><th>AVANCE</th><th>%</th></tr></thead><tbody>{participation.map(row=><tr key={row[0]}>{row.map((value,index)=><td key={index}>{value}</td>)}</tr>)}</tbody></table></article>
    </div>
    <OperationsMatrix title="REPORTE CHS" rows={chs} groups={chsGroups} tone="chs"/>
    <div className="delivery-mini-grid chs-grid">
      <article className="delivery-mini"><h4>FACTURACIÓN Y ENTREGAS POR MARCA</h4><table><thead><tr><th>MARCA</th><th>FACT.</th><th>ENT.</th></tr></thead><tbody>{brandRows.map(row=><tr key={row[0]}>{row.map((value,index)=><td key={index}>{value}</td>)}</tr>)}</tbody></table></article>
      <MiniTable title="CONCILIACIÓN DE ENTREGAS" rows={[["(+) ENTREGAS REALES",deliveredChs.length,'positive'],['(-) REPORTE ANTERIOR','—'],['(+) DEMOS OUT',count(pendingChs,row=>category(row)==='VENTAS DEMO')],['(-) DEMOS FACTURADOS',count(deliveredChs,row=>category(row)==='VENTAS DEMO')],['(-) FLOTILLAS',count(deliveredChs,row=>category(row)==='FLOTILLA')],['(-) PENDIENTES DE REPORTAR',pendingChs.length,'warning'],['(+) REPORTADAS HOY',count(deliveredChs,row=>row.actualDate===today),'positive'],['ENTREGAS REPORTADAS MES',deliveredChs.length,'strong']]}/>
      <MiniTable title="ENTREGAS CADILLAC" rows={[["ENTREGAS",brandRows.find(row=>row[0]==='CADILLAC')?.[2]||0],['DEMOS OUT','—'],['REPORTADAS MES',brandRows.find(row=>row[0]==='CADILLAC')?.[2]||0],['REFERENCIA','—'],['% REF. ENT.','Pendiente','strong']]}/>
      <MiniTable title="ENTREGAS BUICK-GMC" rows={[["ENTREGAS",(brandRows.find(row=>row[0]==='BUICK')?.[2]||0)+(brandRows.find(row=>row[0]==='GMC')?.[2]||0)],['DEMOS OUT','—'],['REPORTADAS MES',deliveredChs.length],['REFERENCIA','—'],['% REF. ENT.','Pendiente','strong']]}/>
    </div>
    <style>{REPORT_CSS}</style><style>{MODERN_REPORT_CSS}</style>
  </section>;
}

const REPORT_CSS=`.delivery-report-suite{display:grid;gap:14px}.delivery-report-suite-title{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 20px;border:1px solid #dbe5f2;border-radius:16px;background:#fff}.delivery-report-suite-title span{color:#2563eb;font-size:9px;font-weight:900;letter-spacing:.12em}.delivery-report-suite-title h3{margin:4px 0;color:#0f2f63}.delivery-report-suite-title p{margin:0;color:#64748b;font-size:10px}.delivery-report-suite-title>b{color:#173d78;text-transform:capitalize}.delivery-report{overflow:hidden;border:1px solid #b8c7d9;border-radius:12px;background:#fff}.delivery-report>header{display:flex;justify-content:space-between;align-items:center;padding:12px 16px;background:#dbe5f2}.delivery-report.chs>header{background:#efd1d1}.delivery-report>header h3{margin:0;color:#111827;font-size:20px}.delivery-report>header span{font-size:12px;font-weight:800;text-transform:capitalize}.delivery-report-scroll{overflow:auto}.delivery-report-matrix{width:100%;min-width:1450px;border-collapse:collapse}.delivery-report-matrix th,.delivery-report-matrix td{padding:6px 5px;border:1px solid #273444;text-align:center;font-size:8px}.delivery-report-matrix thead th{background:#d9e1ea;color:#111827;font-weight:900}.delivery-report-matrix thead th.delivered,.delivery-report-matrix td.delivered{background:#c8f7a0}.delivery-report-matrix .stub{min-width:130px}.delivery-report-matrix tbody th{text-align:left;background:#eef2f7}.delivery-report-matrix td.total{background:#fffda6;font-weight:900}.delivery-report-matrix tr.grand>*{background:#fffda6;font-weight:900}.delivery-report-matrix tr.grand>.delivered{background:#c8f7a0}.delivery-mini-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.delivery-mini-grid.chs-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.delivery-mini{overflow:hidden;border:1px solid #273444;background:#fff}.delivery-mini h4{margin:0;padding:7px 9px;background:#c8f7a0;color:#111827;font-size:9px;text-align:center}.delivery-mini-grid.chs-grid .delivery-mini h4{background:#f3c68f}.delivery-mini table{width:100%;border-collapse:collapse}.delivery-mini th,.delivery-mini td{padding:6px;border:1px solid #273444;font-size:8px}.delivery-mini th{text-align:left}.delivery-mini td{text-align:right;font-weight:900}.delivery-mini tr.positive{color:#dc2626}.delivery-mini tr.warning td{background:#fff200}.delivery-mini tr.strong td{background:#7ac943;color:#111}.delivery-mini.market thead th{background:#eef2f7;text-align:center}.delivery-mini.market tbody tr{color:#dc2626;font-weight:900}@media(max-width:1100px){.delivery-mini-grid,.delivery-mini-grid.chs-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.delivery-report-suite-title{align-items:flex-start;flex-direction:column}.delivery-mini-grid,.delivery-mini-grid.chs-grid{grid-template-columns:1fr}}`;
