import React,{useMemo,useRef,useState} from 'react';
import {AlertTriangle,BarChart3,CarFront,CheckCircle2,Download,FileText,Link2,Search,UsersRound} from 'lucide-react';
import {buildTraceability} from './traceability';

const branchKey=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
const pct=(value,total)=>total?`${(value/total*100).toFixed(1)}%`:'0.0%';
const BDC_STAGES=[['bdcLead','Lead individualizado'],['bdcAppointment','Cita'],['bdcConfirmation','Confirmación'],['bdcEffective','Efectiva'],['bdcApplication','Solicitud'],['bdcClosure','Cierre']];

export default function TraceabilityModule({data,inventoryData,bdcRecords=[],allowedBranches=[],showToast}){
  const[view,setView]=useState('clientes'),[search,setSearch]=useState('');
  const reportRef=useRef(null);
  const allowed=useMemo(()=>new Set((allowedBranches||[]).map(branchKey)),[allowedBranches]);
  const scopedData=useMemo(()=>Object.fromEntries(Object.entries(data||{}).map(([key,value])=>[key,Array.isArray(value)&&allowed.size?value.filter(row=>(!row?.branch&&!row?.sucursal)||allowed.has(branchKey(row.branch||row.sucursal))):value])),[data,allowed]);
  const scopedInventory=useMemo(()=>({...(inventoryData||{}),records:(inventoryData?.records||[]).filter(row=>!allowed.size||branchKey(row.branch)==='TODAS LAS SUCURSALES'||allowed.has(branchKey(row.branch)))}),[inventoryData,allowed]);
  const trace=useMemo(()=>buildTraceability(scopedData,scopedInventory,bdcRecords),[scopedData,scopedInventory,bdcRecords]);
  const query=search.trim().toUpperCase();
  const customers=trace.customerJourneys.filter(row=>!query||[...row.names,...row.phones,...row.emails,...row.sources].join(' ').toUpperCase().includes(query));
  const vehicles=trace.vehicleJourneys.filter(row=>!query||[row.vin,row.unit,row.branch,...row.sources].join(' ').toUpperCase().includes(query));
  const analysis=useMemo(()=>{
    const linked=trace.customerJourneys.filter(row=>row.modules.length>1).length,identified=trace.customerJourneys.filter(row=>row.phones.length||row.emails.length).length;
    const stageCounts=BDC_STAGES.map(([source,label])=>({source,label,value:trace.bdcEvents.filter(event=>event.source===source).length}));
    const stageRates=stageCounts.slice(1).map((stage,index)=>({...stage,previous:stageCounts[index].value,rate:stageCounts[index].value/(stageCounts[index].value||1)}));
    const weakest=[...stageRates.filter(row=>row.previous>0)].sort((a,b)=>a.rate-b.rate)[0]||null,moduleMap=new Map(),branchMap=new Map();
    trace.events.forEach(event=>{const module=event.source.startsWith('bdc')?'BDC':event.label;moduleMap.set(module,(moduleMap.get(module)||0)+1);const name=event.branch||'Sin sucursal',item=branchMap.get(name)||{name,events:0,customers:new Set(),closures:0,deliveries:0};item.events++;if(event.normalizedName)item.customers.add(event.normalizedName);if(event.source==='bdcClosure')item.closures++;if(event.source==='deliveryOperations'&&(event.row.actualDate||String(event.row.status).toUpperCase()==='ENTREGADA'))item.deliveries++;branchMap.set(name,item);});
    const modules=[...moduleMap.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value),branches=[...branchMap.values()].map(row=>({...row,customers:row.customers.size})).sort((a,b)=>b.events-a.events),bdcLeads=stageCounts[0]?.value||0,bdcClosures=stageCounts.at(-1)?.value||0;
    return{linked,identified,unidentified:trace.customerJourneys.length-identified,stageCounts,weakest,modules,branches,bdcLeads,bdcClosures,bdcCloseRate:bdcLeads?bdcClosures/bdcLeads:0};
  },[trace]);

  const exportExcel=async()=>{try{
    const XLSX=await import('xlsx');
    const summary=[{Indicador:'Clientes identificados',Valor:trace.customerJourneys.length},{Indicador:'Clientes con teléfono o correo',Valor:analysis.identified},{Indicador:'Clientes presentes en varios módulos',Valor:analysis.linked},{Indicador:'Etapas individuales BDC',Valor:trace.bdcEvents.length},{Indicador:'Conversión BDC lead individualizado a cierre',Valor:analysis.bdcCloseRate},{Indicador:'Unidades con VIN',Valor:trace.vehicleJourneys.length},{Indicador:'Salidas de inventario identificadas',Valor:trace.retiredInventory.length},{Indicador:'Tomas sin avalúo ligado',Valor:trace.tradeInsWithoutAppraisal.length},{Indicador:'Posibles clientes duplicados',Valor:trace.possibleNameMatches.length},{Indicador:'Inventario sin VIN válido',Valor:trace.inventoryWithoutVin.length}];
    const customerRows=trace.customerJourneys.map(row=>({Cliente:row.names[0]||'Sin nombre','Variantes del nombre':row.names.slice(1).join(' | '),Teléfonos:row.phones.join(' | '),Correos:row.emails.join(' | '),Módulos:row.modules.join(' → '),'Camino completo':row.sources.join(' → '),'Primera actividad':row.firstDate,'Última actividad':row.lastDate,Eventos:row.events.length}));
    const eventRows=trace.events.map(event=>({Fecha:event.date,Cliente:event.name,Teléfono:event.phones.join(' | '),Correo:event.email,Módulo:event.label,Sucursal:event.branch,Unidad:event.unit,VIN:event.vin,Estatus:event.status}));
    const vehicleRows=trace.vehicleJourneys.map(row=>({VIN:row.vin,'VIN válido':row.validVin?'Sí':'No',Unidad:row.unit,Sucursal:row.branch,Recorrido:row.sources.join(' → '),Movimientos:row.events.length}));
    const alertRows=[...trace.tradeInsWithoutAppraisal.map(row=>({Tipo:'Toma sin avalúo',Cliente:row.client,VIN:row.vin,Detalle:`${row.unit||''} · ${row.branch||''}`})),...trace.possibleNameMatches.map(row=>({Tipo:'Posible cliente duplicado',Cliente:row.name,VIN:'',Detalle:`${row.groups} identidades separadas · ${row.events.length} eventos`})),...trace.inventoryWithoutVin.map(row=>({Tipo:'Inventario sin VIN válido',Cliente:'',VIN:row.unitId||'',Detalle:`${row.model||''} · ${row.branch||''}`}))];
    const stages=analysis.stageCounts.map((row,index)=>({Etapa:row.label,Total:row.value,'Conversión desde etapa anterior':index?row.value/(analysis.stageCounts[index-1].value||1):1})),branches=analysis.branches.map(row=>({Sucursal:row.name,Clientes:row.customers,Eventos:row.events,'Cierres BDC':row.closures,Entregas:row.deliveries}));
    const book=XLSX.utils.book_new();[['Resumen ejecutivo',summary],['Embudo BDC',stages],['Por sucursal',branches],['Clientes',customerRows],['Todos los eventos',eventRows],['Unidades',vehicleRows],['Alertas',alertRows]].forEach(([name,rows])=>{const sheet=XLSX.utils.json_to_sheet(rows);sheet['!cols']=Object.keys(rows[0]||{Dato:''}).map(key=>({wch:Math.min(48,Math.max(14,key.length+3))}));XLSX.utils.book_append_sheet(book,sheet,name);});
    XLSX.writeFile(book,`Trazabilidad_integral_${new Date().toISOString().slice(0,10)}.xlsx`);showToast?.('Trazabilidad exportada a Excel.');
  }catch(error){console.error(error);showToast?.('No fue posible exportar la trazabilidad a Excel.','error');}};

  const exportPdf=async()=>{if(!reportRef.current)return;try{
    showToast?.('Generando PDF de trazabilidad…');const[{default:html2canvas},{jsPDF}]=await Promise.all([import('html2canvas'),import('jspdf')]);const canvas=await html2canvas(reportRef.current,{scale:1.25,backgroundColor:'#f4f7fb',useCORS:true,ignoreElements:element=>element.classList?.contains('trace-no-export')}),pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'letter'}),pw=pdf.internal.pageSize.getWidth(),ph=pdf.internal.pageSize.getHeight(),margin=7,uw=pw-margin*2,uh=ph-margin*2,pageHeight=Math.floor(canvas.width*uh/uw);
    for(let offset=0,page=0;offset<canvas.height;offset+=pageHeight,page++){if(page)pdf.addPage();const crop=document.createElement('canvas');crop.width=canvas.width;crop.height=Math.min(pageHeight,canvas.height-offset);crop.getContext('2d').drawImage(canvas,0,offset,canvas.width,crop.height,0,0,canvas.width,crop.height);pdf.addImage(crop.toDataURL('image/jpeg',.92),'JPEG',margin,margin,uw,Math.min(uh,crop.height/crop.width*uw));}
    pdf.save(`Trazabilidad_integral_${new Date().toISOString().slice(0,10)}.pdf`);showToast?.('PDF de trazabilidad generado.');
  }catch(error){console.error(error);showToast?.('No fue posible generar el PDF de trazabilidad.','error');}};

  const weak=analysis.weakest;
  return <div className="trace-module" ref={reportRef}>
    <section className="trace-heading"><div><span>INTELIGENCIA TRANSVERSAL</span><h2>Trazabilidad integral</h2><p>Reconstruye desde el lead BDC hasta la entrega, incluyendo demos, solicitudes, avalúos, tomas y seguros.</p></div><div className="trace-heading-side"><div className="trace-rule"><Link2 size={20}/><b>Cruce automático</b><small>Teléfono, correo y VIN exactos</small></div><div className="trace-export trace-no-export"><button onClick={exportExcel}><Download size={15}/> Excel</button><button className="primary" onClick={exportPdf}><FileText size={15}/> PDF</button></div></div></section>
    <section className="trace-kpis"><article><UsersRound/><span>Clientes identificados</span><strong>{trace.customerJourneys.length}</strong><small>{analysis.linked} aparecen en varios módulos</small></article><article><Link2/><span>Etapas individuales BDC</span><strong>{trace.bdcEvents.length}</strong><small>Lead, cita, confirmación, efectiva y cierre</small></article><article><CarFront/><span>Unidades con VIN</span><strong>{trace.vehicleJourneys.length}</strong><small>Seguimiento individual del ciclo</small></article><article className="good"><CheckCircle2/><span>Salidas de inventario</span><strong>{trace.retiredInventory.length}</strong><small>VIN entregado; histórico conservado</small></article><article className={trace.tradeInsWithoutAppraisal.length?'risk':''}><AlertTriangle/><span>Tomas sin avalúo ligado</span><strong>{trace.tradeInsWithoutAppraisal.length}</strong><small>Requieren regularización</small></article></section>
    <section className="trace-analysis"><header><div><span>LECTURA EJECUTIVA</span><h3>Qué está ocurriendo en el recorrido comercial</h3></div><BarChart3 size={24}/></header><div className="trace-analysis-grid"><article><h4>Conectividad de la información</h4><p>Se identificaron <b>{trace.customerJourneys.length} clientes</b>. De ellos, <b>{analysis.linked} ({pct(analysis.linked,trace.customerJourneys.length)})</b> ya pueden seguirse entre dos o más módulos. {analysis.unidentified?<><b>{analysis.unidentified}</b> no tienen teléfono ni correo suficiente para asegurar el cruce.</>:<>Todos cuentan con teléfono o correo para validar su identidad.</>}</p></article><article><h4>Recorrido BDC individualizado</h4><p>Existen <b>{analysis.bdcLeads} leads identificados a partir de citas</b> y <b>{analysis.bdcClosures} cierres</b>, equivalentes a una conversión observable de <b>{pct(analysis.bdcClosures,analysis.bdcLeads)}</b>. Las asignaciones masivas sin datos personales quedan fuera de este cálculo.</p></article><article className={weak&&weak.rate<.6?'attention':''}><h4>Foco principal</h4><p>{weak?<>La mayor caída está en <b>{weak.label}</b>: avanzan {weak.value} de {weak.previous}, un <b>{pct(weak.value,weak.previous)}</b>. Conviene revisar esta etapa antes de aumentar volumen.</>:<>Aún no hay suficientes etapas BDC individualizadas para determinar la principal pérdida.</>}</p></article><article className={trace.tradeInsWithoutAppraisal.length||trace.inventoryWithoutVin.length?'attention':''}><h4>Calidad y disciplina operativa</h4><p>Hay <b>{trace.tradeInsWithoutAppraisal.length} tomas sin avalúo</b>, <b>{trace.inventoryWithoutVin.length} inventarios sin VIN válido</b> y <b>{trace.possibleNameMatches.length} posibles duplicados</b>. Corregirlos incrementará la precisión de los cruces.</p></article></div><div className="trace-funnel">{analysis.stageCounts.map((stage,index)=>{const previous=index?analysis.stageCounts[index-1].value:stage.value;return <div key={stage.source}><span>{stage.label}</span><strong>{stage.value}</strong><small>{index?`${pct(stage.value,previous)} de la etapa anterior`:'Base individual disponible'}</small><i><b style={{width:`${Math.max(3,stage.value/(analysis.stageCounts[0]?.value||1)*100)}%`}}/></i></div>;})}</div><div className="trace-module-volume">{analysis.modules.map(row=><div key={row.name}><span>{row.name}</span><b>{row.value}</b><i style={{width:`${row.value/(analysis.modules[0]?.value||1)*100}%`}}/></div>)}</div></section>
    <section className="trace-policy"><b>Reglas activas:</b><span>teléfono o correo coincidente = mismo cliente</span><span>VIN de 17 caracteres = misma unidad</span><span>entrega real = salida del inventario activo</span><span>toma nueva = requiere avalúo previo</span><span>nombre solo = posible coincidencia para revisar</span></section>
    <div className="trace-toolbar trace-no-export"><div>{[['clientes','Clientes'],['unidades','Unidades'],['sucursales','Sucursales'],['alertas','Alertas']].map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}>{label}</button>)}</div><label><Search size={15}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Cliente, teléfono, correo, VIN o unidad"/></label></div>
    {view==='clientes'&&<section className="trace-card"><header><div><h3>Camino del cliente</h3><p>Una fila agrupa registros unidos por teléfono o correo. Los nombres distintos permanecen visibles.</p></div></header><div className="trace-table"><table><thead><tr><th>Cliente / variantes</th><th>Identificadores</th><th>Camino detectado</th><th>Primera actividad</th><th>Última actividad</th><th>Eventos</th></tr></thead><tbody>{customers.map(row=><tr key={row.id}><td><b>{row.names[0]||'Sin nombre'}</b>{row.names.slice(1).map(name=><small key={name}>También capturado como: {name}</small>)}</td><td>{row.phones.map(phone=><small key={phone}>Tel. {phone}</small>)}{row.emails.map(email=><small key={email}>{email}</small>)}{!row.phones.length&&!row.emails.length&&<em>Sin identificador único</em>}</td><td><div className="trace-steps">{row.sources.map((source,index)=><React.Fragment key={`${source}-${index}`}><span>{source}</span>{index<row.sources.length-1&&<i>→</i>}</React.Fragment>)}</div></td><td>{row.firstDate||'—'}</td><td>{row.lastDate||'—'}</td><td><b>{row.events.length}</b></td></tr>)}{!customers.length&&<tr><td colSpan="6" className="empty">No hay coincidencias para mostrar.</td></tr>}</tbody></table></div></section>}
    {view==='unidades'&&<section className="trace-card"><header><div><h3>Ciclo de vida por VIN</h3><p>Inventario, demostración, avalúo, toma, seguro y entrega se enlazan por la serie completa.</p></div></header><div className="trace-table"><table><thead><tr><th>VIN</th><th>Unidad</th><th>Sucursal</th><th>Recorrido</th><th>Estatus</th><th>Movimientos</th></tr></thead><tbody>{vehicles.map(row=>{const delivered=row.events.some(event=>event.source==='deliveryOperations'&&(event.row.actualDate||event.row.status==='ENTREGADA'));return <tr key={row.vin}><td><b>{row.vin}</b>{!row.validVin&&<small className="warn">VIN incompleto o inválido</small>}</td><td>{row.unit||'—'}</td><td>{row.branch||'—'}</td><td><div className="trace-steps">{row.sources.map((source,index)=><React.Fragment key={`${source}-${index}`}><span>{source}</span>{index<row.sources.length-1&&<i>→</i>}</React.Fragment>)}</div></td><td><span className={`trace-status ${delivered?'closed':'active'}`}>{delivered?'ENTREGADA / SALIDA':'ACTIVA'}</span></td><td><b>{row.events.length}</b></td></tr>})}{!vehicles.length&&<tr><td colSpan="6" className="empty">No hay unidades con VIN para mostrar.</td></tr>}</tbody></table></div></section>}
    {view==='sucursales'&&<section className="trace-card"><header><div><h3>Trazabilidad por sucursal</h3><p>Volumen identificable, cierres BDC y entregas relacionadas dentro del alcance autorizado.</p></div></header><div className="trace-table"><table><thead><tr><th>Sucursal</th><th>Clientes identificados</th><th>Eventos trazables</th><th>Cierres BDC</th><th>Entregas</th></tr></thead><tbody>{analysis.branches.map(row=><tr key={row.name}><td><b>{row.name}</b></td><td>{row.customers}</td><td>{row.events}</td><td>{row.closures}</td><td>{row.deliveries}</td></tr>)}</tbody></table></div></section>}
    {view==='alertas'&&<div className="trace-alert-grid"><section className="trace-card"><header><div><h3>Tomas sin avalúo previo</h3><p>Registros históricos sin un VIN coincidente en Avalúos.</p></div></header><ul>{trace.tradeInsWithoutAppraisal.map(row=><li key={row.id}><b>{row.client||'Sin cliente'}</b><span>{row.vin||'Sin VIN'} · {row.unit||'Sin unidad'} · {row.branch||'Sin sucursal'}</span></li>)}{!trace.tradeInsWithoutAppraisal.length&&<li className="ok">Todas las tomas tienen avalúo relacionado.</li>}</ul></section><section className="trace-card"><header><div><h3>Posibles clientes duplicados</h3><p>Mismo nombre normalizado, sin teléfono o correo que confirme el cruce.</p></div></header><ul>{trace.possibleNameMatches.map(row=><li key={row.name}><b>{row.name}</b><span>{row.groups} identidades separadas · {row.events.length} eventos</span></li>)}{!trace.possibleNameMatches.length&&<li className="ok">No hay coincidencias dudosas por nombre.</li>}</ul></section><section className="trace-card"><header><div><h3>Inventario sin VIN válido</h3><p>No puede darse de baja automáticamente hasta completar la serie.</p></div></header><ul>{trace.inventoryWithoutVin.slice(0,30).map(row=><li key={row.id}><b>{row.model||'Sin modelo'}</b><span>{row.branch||'Sin sucursal'} · {row.unitId||'VIN no capturado'}</span></li>)}{!trace.inventoryWithoutVin.length&&<li className="ok">Todo el inventario tiene VIN válido.</li>}</ul></section></div>}
    <style>{TRACE_CSS}</style>
  </div>;
}

const TRACE_CSS=`
.trace-module{display:grid;gap:14px}.trace-heading{display:flex;justify-content:space-between;align-items:center;gap:18px;padding:20px 22px;border:1px solid #dbe5f2;border-radius:16px;background:#fff}.trace-heading>div>span,.trace-analysis header span{color:#2563eb;font-size:9px;font-weight:900;letter-spacing:.13em}.trace-heading h2{margin:4px 0;color:#0f2f63;font-size:22px}.trace-heading p,.trace-card header p{margin:0;color:#64748b;font-size:11px}.trace-heading-side{display:flex;align-items:center;gap:9px}.trace-rule{display:grid;grid-template-columns:auto 1fr;gap:2px 8px;align-items:center;padding:12px 15px;border-radius:12px;background:#eff6ff;color:#1d4ed8}.trace-rule svg{grid-row:span 2}.trace-rule small{color:#58708f}.trace-export{display:flex;gap:6px}.trace-export button{display:inline-flex;align-items:center;gap:6px;padding:10px 12px;border:1px solid #cbd8e8;border-radius:9px;background:#fff;color:#244875;font-size:10px;font-weight:900}.trace-export button.primary{border-color:#2563eb;background:#2563eb;color:#fff}
.trace-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.trace-kpis article{display:grid;grid-template-columns:auto 1fr;gap:2px 9px;padding:15px;border:1px solid #dbe5f2;border-radius:14px;background:#fff}.trace-kpis svg{grid-row:span 3;color:#2563eb}.trace-kpis span{color:#64748b;font-size:8px;font-weight:900;text-transform:uppercase}.trace-kpis strong{color:#0f2f63;font-size:23px}.trace-kpis small{color:#64748b}.trace-kpis article.risk{border-color:#fecaca;background:#fff7f7}.trace-kpis article.risk svg{color:#dc2626}.trace-kpis article.good svg{color:#16a34a}
.trace-analysis{overflow:hidden;border:1px solid #bfdbfe;border-radius:16px;background:linear-gradient(145deg,#eff6ff,#fff)}.trace-analysis>header{display:flex;justify-content:space-between;align-items:center;padding:17px 20px;border-bottom:1px solid #dbeafe}.trace-analysis header h3{margin:4px 0 0;color:#173d78}.trace-analysis header svg{color:#2563eb}.trace-analysis-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;padding:14px}.trace-analysis-grid article{padding:14px;border:1px solid #dbe5f2;border-radius:12px;background:#fff}.trace-analysis-grid article.attention{border-color:#fed7aa;background:#fffaf2}.trace-analysis-grid h4{margin:0 0 7px;color:#173d78;font-size:11px}.trace-analysis-grid p{margin:0;color:#526884;font-size:10px;line-height:1.6}.trace-analysis-grid b{color:#0f2f63}.trace-funnel{display:grid;grid-template-columns:repeat(6,1fr);gap:1px;margin:0 14px 14px;overflow:hidden;border:1px solid #dbe5f2;border-radius:12px;background:#dbe5f2}.trace-funnel>div{display:grid;gap:5px;padding:12px;background:#fff}.trace-funnel span{min-height:24px;color:#64748b;font-size:8px;font-weight:900;text-transform:uppercase}.trace-funnel strong{color:#0f2f63;font-size:20px}.trace-funnel small{color:#64748b;font-size:8px}.trace-funnel i{height:5px;overflow:hidden;border-radius:999px;background:#e2e8f0}.trace-funnel i b{display:block;height:100%;border-radius:999px;background:#2563eb}.trace-module-volume{display:flex;flex-wrap:wrap;gap:7px;padding:0 14px 14px}.trace-module-volume>div{position:relative;display:flex;gap:8px;min-width:125px;padding:8px 10px;overflow:hidden;border:1px solid #dbe5f2;border-radius:9px;background:#fff}.trace-module-volume span,.trace-module-volume b{position:relative;z-index:1;font-size:9px}.trace-module-volume span{flex:1;color:#526884}.trace-module-volume i{position:absolute;left:0;bottom:0;height:3px;background:#60a5fa}
.trace-policy{display:flex;align-items:center;flex-wrap:wrap;gap:7px;padding:12px 14px;border:1px solid #bfdbfe;border-radius:13px;background:#f8fbff;color:#415b7d;font-size:10px}.trace-policy b{color:#173d78}.trace-policy span{padding:6px 8px;border-radius:8px;background:#fff}.trace-toolbar{display:flex;justify-content:space-between;gap:12px}.trace-toolbar>div{display:flex;gap:5px;padding:4px;border-radius:11px;background:#e8eef8}.trace-toolbar button{padding:9px 14px;border:0;border-radius:8px;background:transparent;color:#64748b;font-weight:800}.trace-toolbar button.active{background:#fff;color:#1d4ed8}.trace-toolbar label{display:flex;align-items:center;gap:7px;width:min(420px,100%);padding:0 10px;border:1px solid #cbd8e8;border-radius:10px;background:#fff}.trace-toolbar input{width:100%;padding:10px 0;border:0;outline:0}.trace-card{overflow:hidden;border:1px solid #dbe5f2;border-radius:16px;background:#fff}.trace-card header{padding:15px 18px;border-bottom:1px solid #e5eaf2}.trace-card h3{margin:0 0 3px;color:#173d78}.trace-table{overflow:auto}.trace-table table{width:100%;min-width:850px;border-collapse:collapse}.trace-table th{padding:10px;background:#edf3fb;color:#526884;font-size:8px;text-align:left;text-transform:uppercase}.trace-table td{padding:11px;border-top:1px solid #e5eaf2;color:#17345f;font-size:10px;vertical-align:top}.trace-table td small{display:block;margin-top:3px;color:#64748b}.trace-table td small.warn{color:#dc2626;font-weight:800}.trace-table em{color:#d97706}.trace-steps{display:flex;align-items:center;flex-wrap:wrap;gap:4px}.trace-steps span{padding:5px 7px;border-radius:7px;background:#eff6ff;color:#1746a2;font-weight:800}.trace-steps i{color:#94a3b8}.trace-status{display:inline-flex;padding:6px 8px;border-radius:999px;font-size:8px;font-weight:900}.trace-status.active{background:#dcfce7;color:#15803d}.trace-status.closed{background:#e2e8f0;color:#475569}.trace-alert-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.trace-card ul{display:grid;gap:0;margin:0;padding:0;list-style:none}.trace-card li{display:grid;gap:3px;padding:11px 16px;border-top:1px solid #eef2f7;font-size:10px}.trace-card li:first-child{border-top:0}.trace-card li span{color:#64748b}.trace-card li.ok{color:#15803d;font-weight:800}.empty{text-align:center!important;padding:35px!important;color:#94a3b8!important}
@media(max-width:1100px){.trace-analysis-grid{grid-template-columns:repeat(2,1fr)}.trace-funnel{grid-template-columns:repeat(3,1fr)}.trace-heading-side{align-items:flex-end;flex-direction:column}}@media(max-width:800px){.trace-alert-grid{grid-template-columns:1fr}.trace-heading,.trace-toolbar{align-items:flex-start;flex-direction:column}.trace-heading-side{width:100%;align-items:stretch}.trace-export button{flex:1}.trace-analysis-grid,.trace-funnel{grid-template-columns:1fr}.trace-toolbar label{width:100%}}
`;
